-- RLS policy upgrade for databases migrated BEFORE the domain-persistence tables were added.
--
-- WHO NEEDS THIS. `prisma migrate deploy` never re-runs a migration that is already recorded in
-- _prisma_migrations. 20260923090000_part11_row_level_security is regenerated by
-- scripts/gen_part11_rls.py whenever tenant tables are added (see the note at the top of
-- 20260923080000_developer_platform_mobile_release). A database that applied an older version of
-- it (153 policies, upstream 71ff495) therefore gets the new tables from the earlier-stamped
-- migrations but NOT their tenant_isolation policies. Fresh databases do not need this file:
-- the current migration already creates all 182 policies.
--
-- WHAT IT DOES. Creates the tenant_isolation policy on the 29 tenant tables covered since then.
-- Every CREATE POLICY below is copied byte-for-byte from the generated migration; nothing else
-- is changed. Each is preceded by DROP POLICY IF EXISTS, so the file is safe to run more than
-- once, and the whole file is one transaction, so it applies completely or not at all.
-- Like the migration, it does NOT enable RLS: that stays the DBA step in prisma/rls/enable.sql.
--
-- ORDER.
--   1. prisma migrate deploy            (creates the new tables)
--   2. this file, either of:
--        npx prisma db execute --schema apps/api/prisma/schema.prisma --file apps/api/prisma/upgrades/rls_policies_153_to_182.sql
--        psql "$DIRECT_DATABASE_URL" -v ON_ERROR_STOP=1 -f apps/api/prisma/upgrades/rls_policies_153_to_182.sql
--   3. prisma/rls/enable.sql            (only if RLS is, or is being, enabled; follow its pre-flight checklist)
--      Never run step 3 before step 2: a table with RLS forced and no policy returns zero rows.
--      Full procedure: docs/PART11_ROW_LEVEL_SECURITY.md
--
-- CHECK AFTERWARDS (expects 182):
--   SELECT count(*) FROM pg_policies WHERE policyname = 'tenant_isolation';

BEGIN;

-- Idempotent; identical to the definition in the migration.
CREATE OR REPLACE FUNCTION wlct_current_tenant_id() RETURNS uuid
LANGUAGE sql STABLE
AS $$ SELECT nullif(current_setting('app.tenant_id', true), '')::uuid $$;

-- BillingCustomer
DROP POLICY IF EXISTS tenant_isolation ON "billing_customers";
CREATE POLICY tenant_isolation ON "billing_customers"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- BillingLedgerEntry
DROP POLICY IF EXISTS tenant_isolation ON "billing_ledger_entries";
CREATE POLICY tenant_isolation ON "billing_ledger_entries"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ComplianceReportCertification
DROP POLICY IF EXISTS tenant_isolation ON "compliance_report_certifications";
CREATE POLICY tenant_isolation ON "compliance_report_certifications"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ComplianceReportDelivery
DROP POLICY IF EXISTS tenant_isolation ON "compliance_report_deliveries";
CREATE POLICY tenant_isolation ON "compliance_report_deliveries"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ComplianceReportValidation
DROP POLICY IF EXISTS tenant_isolation ON "compliance_report_validations";
CREATE POLICY tenant_isolation ON "compliance_report_validations"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ComplianceReport
DROP POLICY IF EXISTS tenant_isolation ON "compliance_reports";
CREATE POLICY tenant_isolation ON "compliance_reports"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ConsentRecord
DROP POLICY IF EXISTS tenant_isolation ON "consent_records";
CREATE POLICY tenant_isolation ON "consent_records"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- DeveloperAccessToken
DROP POLICY IF EXISTS tenant_isolation ON "developer_access_tokens";
CREATE POLICY tenant_isolation ON "developer_access_tokens"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- DeveloperApplication
DROP POLICY IF EXISTS tenant_isolation ON "developer_applications";
CREATE POLICY tenant_isolation ON "developer_applications"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- DeveloperAudit
DROP POLICY IF EXISTS tenant_isolation ON "developer_audit";
CREATE POLICY tenant_isolation ON "developer_audit"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- DeveloperCredential
DROP POLICY IF EXISTS tenant_isolation ON "developer_credentials";
CREATE POLICY tenant_isolation ON "developer_credentials"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- DeveloperEventSubscription
DROP POLICY IF EXISTS tenant_isolation ON "developer_event_subscriptions";
CREATE POLICY tenant_isolation ON "developer_event_subscriptions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- DeveloperOAuthGrant
DROP POLICY IF EXISTS tenant_isolation ON "developer_oauth_grants";
CREATE POLICY tenant_isolation ON "developer_oauth_grants"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- DeveloperWebhookDelivery
DROP POLICY IF EXISTS tenant_isolation ON "developer_webhook_deliveries";
CREATE POLICY tenant_isolation ON "developer_webhook_deliveries"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- DeveloperWebhookSubscription
DROP POLICY IF EXISTS tenant_isolation ON "developer_webhook_subscriptions";
CREATE POLICY tenant_isolation ON "developer_webhook_subscriptions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- EvidencePackage
DROP POLICY IF EXISTS tenant_isolation ON "evidence_packages";
CREATE POLICY tenant_isolation ON "evidence_packages"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- FeeAuditLog
DROP POLICY IF EXISTS tenant_isolation ON "fee_audit_logs";
CREATE POLICY tenant_isolation ON "fee_audit_logs"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- FeeSettlementItem
DROP POLICY IF EXISTS tenant_isolation ON "fee_settlement_items";
CREATE POLICY tenant_isolation ON "fee_settlement_items"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- FinanceAuditLog
DROP POLICY IF EXISTS tenant_isolation ON "finance_audit_logs";
CREATE POLICY tenant_isolation ON "finance_audit_logs"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- GovernanceAction
DROP POLICY IF EXISTS tenant_isolation ON "governance_actions";
CREATE POLICY tenant_isolation ON "governance_actions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- GovernanceAudit
DROP POLICY IF EXISTS tenant_isolation ON "governance_audits";
CREATE POLICY tenant_isolation ON "governance_audits"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- GovernanceDataClassification
DROP POLICY IF EXISTS tenant_isolation ON "governance_data_classifications";
CREATE POLICY tenant_isolation ON "governance_data_classifications"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- GovernanceDataInventory
DROP POLICY IF EXISTS tenant_isolation ON "governance_data_inventory";
CREATE POLICY tenant_isolation ON "governance_data_inventory"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- GovernanceReconciliation
DROP POLICY IF EXISTS tenant_isolation ON "governance_reconciliations";
CREATE POLICY tenant_isolation ON "governance_reconciliations"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- PrivacyExport
DROP POLICY IF EXISTS tenant_isolation ON "privacy_exports";
CREATE POLICY tenant_isolation ON "privacy_exports"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- PrivacyRequest
DROP POLICY IF EXISTS tenant_isolation ON "privacy_requests";
CREATE POLICY tenant_isolation ON "privacy_requests"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- RetentionCandidate
DROP POLICY IF EXISTS tenant_isolation ON "retention_candidates";
CREATE POLICY tenant_isolation ON "retention_candidates"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- SaasAuditLog
DROP POLICY IF EXISTS tenant_isolation ON "saas_audit_logs";
CREATE POLICY tenant_isolation ON "saas_audit_logs"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- UsageBucket
DROP POLICY IF EXISTS tenant_isolation ON "usage_buckets";
CREATE POLICY tenant_isolation ON "usage_buckets"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

COMMIT;
