-- RLS policy upgrade for databases migrated BEFORE the Part 11 SSO tables were added.
--
-- WHO NEEDS THIS. `prisma migrate deploy` never re-runs a migration that is already recorded in
-- _prisma_migrations. 20260923090000_part11_row_level_security is regenerated by
-- scripts/gen_part11_rls.py whenever tenant tables are added. A database that applied the previous
-- version of it (182 policies; see rls_policies_153_to_182.sql for older databases) gets the four
-- SSO tables from 20260923089000_sso_authorization_code_flow but NOT their tenant_isolation
-- policies. Fresh databases do not need this file: the current migration creates all 186 policies.
--
-- WHAT IT DOES. Creates the tenant_isolation policy on the 4 tenant tables added by Part 11:
-- sso_assertion_replays, sso_audit_events, sso_auth_transactions, sso_identities.
-- Every CREATE POLICY below is copied byte-for-byte from the generated migration; nothing else
-- is changed. Each is preceded by DROP POLICY IF EXISTS, so the file is safe to run more than
-- once, and the whole file is one transaction, so it applies completely or not at all.
-- Like the migration, it does NOT enable RLS: that stays the DBA step in prisma/rls/enable.sql.
--
-- ORDER.
--   1. prisma migrate deploy            (creates the new tables)
--   2. rls_policies_153_to_182.sql      (only if the database predates the 182-policy version)
--   3. this file, either of:
--        npx prisma db execute --schema apps/api/prisma/schema.prisma --file apps/api/prisma/upgrades/rls_policies_182_to_186.sql
--        psql "$DIRECT_DATABASE_URL" -v ON_ERROR_STOP=1 -f apps/api/prisma/upgrades/rls_policies_182_to_186.sql
--   4. prisma/rls/enable.sql            (only if RLS is, or is being, enabled; follow its pre-flight checklist)
--      Never run step 4 before step 3: a table with RLS forced and no policy returns zero rows.
--      Full procedure: docs/PART11_ROW_LEVEL_SECURITY.md
--
-- CHECK AFTERWARDS (expects 186):
--   SELECT count(*) FROM pg_policies WHERE policyname = 'tenant_isolation';

BEGIN;

-- Idempotent; identical to the definition in the migration.
CREATE OR REPLACE FUNCTION wlct_current_tenant_id() RETURNS uuid
LANGUAGE sql STABLE
AS $$ SELECT nullif(current_setting('app.tenant_id', true), '')::uuid $$;

-- SsoAssertionReplay
DROP POLICY IF EXISTS tenant_isolation ON "sso_assertion_replays";
CREATE POLICY tenant_isolation ON "sso_assertion_replays"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- SsoAuditEvent
DROP POLICY IF EXISTS tenant_isolation ON "sso_audit_events";
CREATE POLICY tenant_isolation ON "sso_audit_events"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- SsoAuthTransaction
DROP POLICY IF EXISTS tenant_isolation ON "sso_auth_transactions";
CREATE POLICY tenant_isolation ON "sso_auth_transactions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- SsoIdentity
DROP POLICY IF EXISTS tenant_isolation ON "sso_identities";
CREATE POLICY tenant_isolation ON "sso_identities"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

COMMIT;
