-- Part 11 (enable: the DBA step). Generated by scripts/gen_part11_rls.py - do not hand-edit;
-- rerun the generator. Schema stamp: 20260923090000.
--
-- Row-level security is the layer BELOW the tenant-scoped Prisma factory: the
-- factory cannot forget its WHERE, and even if a path bypassed the factory,
-- the database would still refuse the row. No GUC means no rows:
-- `wlct_current_tenant_id()` returns NULL when `app.tenant_id` is unset, and
-- `tenant_id = NULL` is never true - fail-closed, which is the only
-- acceptable default for a defence layer.

-- PRE-FLIGHT CHECKLIST - all of it, or do not run this file:
--
--  1. Every API write/read path for a covered table runs inside
--     PrismaService.withTenantRls(tenantId, ...) (which issues
--     set_config('app.tenant_id', $1, true) as the transaction's first
--     statement). Grep the module for direct prisma.<model> usage outside
--     the scoped client as part of the review.
--  2. The application role has neither BYPASSRLS nor superuser:
--        SELECT rolname, rolbypassrls, rolsuper
--        FROM pg_roles WHERE rolname = current_user;
--     FORCE below covers the table OWNER; it does not cover those two
--     privileges, and a role that has them makes the whole exercise
--     theatre. Deployment roles get exactly what they need, nothing more.
--  3. Queue-side writers (audit, alerts, incidents - the excluded nullable
--     tables) are confirmed unaffected: they are not covered here.
--  4. Rollback rehearsed: prisma/rls/disable.sql returns to today's state
--     exactly (NO FORCE, DISABLE, then the migration's objects stay
--     defined and inert).
--  5. Run at low traffic. Enabling is a catalog flip per table; in-flight
--     transactions without the GUC start seeing zero rows immediately -
--     which is the point, and the reason it is a scheduled operation.

-- --- covered tables (186) -------------------------------------------
ALTER TABLE "account_balance_snapshots" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "account_balance_snapshots" FORCE ROW LEVEL SECURITY;
ALTER TABLE "account_ownerships" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "account_ownerships" FORCE ROW LEVEL SECURITY;
ALTER TABLE "account_relationships" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "account_relationships" FORCE ROW LEVEL SECURITY;
ALTER TABLE "account_restrictions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "account_restrictions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "backtest_metrics" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "backtest_metrics" FORCE ROW LEVEL SECURITY;
ALTER TABLE "backtest_runs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "backtest_runs" FORCE ROW LEVEL SECURITY;
ALTER TABLE "backtest_trades" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "backtest_trades" FORCE ROW LEVEL SECURITY;
ALTER TABLE "billing_customers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "billing_customers" FORCE ROW LEVEL SECURITY;
ALTER TABLE "billing_ledger_entries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "billing_ledger_entries" FORCE ROW LEVEL SECURITY;
ALTER TABLE "billing_notification_audit_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "billing_notification_audit_logs" FORCE ROW LEVEL SECURITY;
ALTER TABLE "billing_notification_jobs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "billing_notification_jobs" FORCE ROW LEVEL SECURITY;
ALTER TABLE "billing_notification_preferences" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "billing_notification_preferences" FORCE ROW LEVEL SECURITY;
ALTER TABLE "client_lifecycle_audits" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "client_lifecycle_audits" FORCE ROW LEVEL SECURITY;
ALTER TABLE "client_onboarding_steps" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "client_onboarding_steps" FORCE ROW LEVEL SECURITY;
ALTER TABLE "client_onboardings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "client_onboardings" FORCE ROW LEVEL SECURITY;
ALTER TABLE "client_profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "client_profiles" FORCE ROW LEVEL SECURITY;
ALTER TABLE "client_reviews" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "client_reviews" FORCE ROW LEVEL SECURITY;
ALTER TABLE "compliance_audit_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "compliance_audit_logs" FORCE ROW LEVEL SECURITY;
ALTER TABLE "compliance_cases" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "compliance_cases" FORCE ROW LEVEL SECURITY;
ALTER TABLE "compliance_evidences" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "compliance_evidences" FORCE ROW LEVEL SECURITY;
ALTER TABLE "compliance_report_certifications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "compliance_report_certifications" FORCE ROW LEVEL SECURITY;
ALTER TABLE "compliance_report_deliveries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "compliance_report_deliveries" FORCE ROW LEVEL SECURITY;
ALTER TABLE "compliance_report_validations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "compliance_report_validations" FORCE ROW LEVEL SECURITY;
ALTER TABLE "compliance_reports" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "compliance_reports" FORCE ROW LEVEL SECURITY;
ALTER TABLE "compliance_reviews" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "compliance_reviews" FORCE ROW LEVEL SECURITY;
ALTER TABLE "compliance_screening_requests" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "compliance_screening_requests" FORCE ROW LEVEL SECURITY;
ALTER TABLE "consent_records" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "consent_records" FORCE ROW LEVEL SECURITY;
ALTER TABLE "copy_executions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "copy_executions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "copy_reconciliation_records" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "copy_reconciliation_records" FORCE ROW LEVEL SECURITY;
ALTER TABLE "copy_subscriptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "copy_subscriptions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "copy_trading_audit_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "copy_trading_audit_logs" FORCE ROW LEVEL SECURITY;
ALTER TABLE "custody_audits" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "custody_audits" FORCE ROW LEVEL SECURITY;
ALTER TABLE "custody_deposits" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "custody_deposits" FORCE ROW LEVEL SECURITY;
ALTER TABLE "custody_internal_transfers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "custody_internal_transfers" FORCE ROW LEVEL SECURITY;
ALTER TABLE "custody_reconciliations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "custody_reconciliations" FORCE ROW LEVEL SECURITY;
ALTER TABLE "custody_reserves" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "custody_reserves" FORCE ROW LEVEL SECURITY;
ALTER TABLE "custody_sweeps" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "custody_sweeps" FORCE ROW LEVEL SECURITY;
ALTER TABLE "custody_transaction_confirmations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "custody_transaction_confirmations" FORCE ROW LEVEL SECURITY;
ALTER TABLE "custody_transactions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "custody_transactions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "custody_wallet_addresses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "custody_wallet_addresses" FORCE ROW LEVEL SECURITY;
ALTER TABLE "custody_wallets" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "custody_wallets" FORCE ROW LEVEL SECURITY;
ALTER TABLE "custody_withdrawals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "custody_withdrawals" FORCE ROW LEVEL SECURITY;
ALTER TABLE "developer_access_tokens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "developer_access_tokens" FORCE ROW LEVEL SECURITY;
ALTER TABLE "developer_applications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "developer_applications" FORCE ROW LEVEL SECURITY;
ALTER TABLE "developer_audit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "developer_audit" FORCE ROW LEVEL SECURITY;
ALTER TABLE "developer_credentials" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "developer_credentials" FORCE ROW LEVEL SECURITY;
ALTER TABLE "developer_event_subscriptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "developer_event_subscriptions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "developer_oauth_grants" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "developer_oauth_grants" FORCE ROW LEVEL SECURITY;
ALTER TABLE "developer_webhook_deliveries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "developer_webhook_deliveries" FORCE ROW LEVEL SECURITY;
ALTER TABLE "developer_webhook_subscriptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "developer_webhook_subscriptions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "device_trusts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "device_trusts" FORCE ROW LEVEL SECURITY;
ALTER TABLE "dunning_cases" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "dunning_cases" FORCE ROW LEVEL SECURITY;
ALTER TABLE "engine_incidents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "engine_incidents" FORCE ROW LEVEL SECURITY;
ALTER TABLE "engine_order_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "engine_order_events" FORCE ROW LEVEL SECURITY;
ALTER TABLE "engine_order_fills" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "engine_order_fills" FORCE ROW LEVEL SECURITY;
ALTER TABLE "engine_orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "engine_orders" FORCE ROW LEVEL SECURITY;
ALTER TABLE "engine_retention_runs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "engine_retention_runs" FORCE ROW LEVEL SECURITY;
ALTER TABLE "enterprise_api_keys" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "enterprise_api_keys" FORCE ROW LEVEL SECURITY;
ALTER TABLE "evidence_packages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "evidence_packages" FORCE ROW LEVEL SECURITY;
ALTER TABLE "exchange_stream_sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "exchange_stream_sessions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "execution_incidents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "execution_incidents" FORCE ROW LEVEL SECURITY;
ALTER TABLE "fee_accruals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fee_accruals" FORCE ROW LEVEL SECURITY;
ALTER TABLE "fee_audit_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fee_audit_logs" FORCE ROW LEVEL SECURITY;
ALTER TABLE "fee_settlement_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fee_settlement_items" FORCE ROW LEVEL SECURITY;
ALTER TABLE "fee_settlements" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "fee_settlements" FORCE ROW LEVEL SECURITY;
ALTER TABLE "finance_audit_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "finance_audit_logs" FORCE ROW LEVEL SECURITY;
ALTER TABLE "funding_approvals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "funding_approvals" FORCE ROW LEVEL SECURITY;
ALTER TABLE "funding_reconciliations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "funding_reconciliations" FORCE ROW LEVEL SECURITY;
ALTER TABLE "funding_requests" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "funding_requests" FORCE ROW LEVEL SECURITY;
ALTER TABLE "governance_actions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "governance_actions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "governance_audits" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "governance_audits" FORCE ROW LEVEL SECURITY;
ALTER TABLE "governance_data_classifications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "governance_data_classifications" FORCE ROW LEVEL SECURITY;
ALTER TABLE "governance_data_inventory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "governance_data_inventory" FORCE ROW LEVEL SECURITY;
ALTER TABLE "governance_reconciliations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "governance_reconciliations" FORCE ROW LEVEL SECURITY;
ALTER TABLE "institutional_accounts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "institutional_accounts" FORCE ROW LEVEL SECURITY;
ALTER TABLE "invoices" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "invoices" FORCE ROW LEVEL SECURITY;
ALTER TABLE "kyc_profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "kyc_profiles" FORCE ROW LEVEL SECURITY;
ALTER TABLE "login_attempts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "login_attempts" FORCE ROW LEVEL SECURITY;
ALTER TABLE "mobile_applications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "mobile_applications" FORCE ROW LEVEL SECURITY;
ALTER TABLE "mobile_artifacts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "mobile_artifacts" FORCE ROW LEVEL SECURITY;
ALTER TABLE "mobile_builds" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "mobile_builds" FORCE ROW LEVEL SECURITY;
ALTER TABLE "mobile_crash_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "mobile_crash_events" FORCE ROW LEVEL SECURITY;
ALTER TABLE "mobile_release_approvals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "mobile_release_approvals" FORCE ROW LEVEL SECURITY;
ALTER TABLE "mobile_release_rollouts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "mobile_release_rollouts" FORCE ROW LEVEL SECURITY;
ALTER TABLE "mobile_releases" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "mobile_releases" FORCE ROW LEVEL SECURITY;
ALTER TABLE "mobile_security_scans" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "mobile_security_scans" FORCE ROW LEVEL SECURITY;
ALTER TABLE "mobile_store_submissions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "mobile_store_submissions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "notifications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "notifications" FORCE ROW LEVEL SECURITY;
ALTER TABLE "oms_allocations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "oms_allocations" FORCE ROW LEVEL SECURITY;
ALTER TABLE "oms_audits" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "oms_audits" FORCE ROW LEVEL SECURITY;
ALTER TABLE "oms_execution_acks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "oms_execution_acks" FORCE ROW LEVEL SECURITY;
ALTER TABLE "oms_execution_latency" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "oms_execution_latency" FORCE ROW LEVEL SECURITY;
ALTER TABLE "oms_execution_quality" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "oms_execution_quality" FORCE ROW LEVEL SECURITY;
ALTER TABLE "oms_fills" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "oms_fills" FORCE ROW LEVEL SECURITY;
ALTER TABLE "oms_operational" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "oms_operational" FORCE ROW LEVEL SECURITY;
ALTER TABLE "oms_order_intents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "oms_order_intents" FORCE ROW LEVEL SECURITY;
ALTER TABLE "oms_post_trades" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "oms_post_trades" FORCE ROW LEVEL SECURITY;
ALTER TABLE "oms_reconciliations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "oms_reconciliations" FORCE ROW LEVEL SECURITY;
ALTER TABLE "oms_rejections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "oms_rejections" FORCE ROW LEVEL SECURITY;
ALTER TABLE "oms_trades" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "oms_trades" FORCE ROW LEVEL SECURITY;
ALTER TABLE "oms_venue_scores" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "oms_venue_scores" FORCE ROW LEVEL SECURITY;
ALTER TABLE "orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "orders" FORCE ROW LEVEL SECURITY;
ALTER TABLE "overage_records" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "overage_records" FORCE ROW LEVEL SECURITY;
ALTER TABLE "paper_portfolio_snapshots" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "paper_portfolio_snapshots" FORCE ROW LEVEL SECURITY;
ALTER TABLE "paper_trading_sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "paper_trading_sessions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "payments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "payments" FORCE ROW LEVEL SECURITY;
ALTER TABLE "payouts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "payouts" FORCE ROW LEVEL SECURITY;
ALTER TABLE "portfolio_accounting_adjustments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "portfolio_accounting_adjustments" FORCE ROW LEVEL SECURITY;
ALTER TABLE "portfolio_accounting_closes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "portfolio_accounting_closes" FORCE ROW LEVEL SECURITY;
ALTER TABLE "portfolio_accounting_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "portfolio_accounting_events" FORCE ROW LEVEL SECURITY;
ALTER TABLE "portfolio_accounting_periods" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "portfolio_accounting_periods" FORCE ROW LEVEL SECURITY;
ALTER TABLE "portfolio_accounting_profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "portfolio_accounting_profiles" FORCE ROW LEVEL SECURITY;
ALTER TABLE "portfolio_accounting_reconciliations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "portfolio_accounting_reconciliations" FORCE ROW LEVEL SECURITY;
ALTER TABLE "portfolio_attribution_records" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "portfolio_attribution_records" FORCE ROW LEVEL SECURITY;
ALTER TABLE "portfolio_cash_ledger_entries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "portfolio_cash_ledger_entries" FORCE ROW LEVEL SECURITY;
ALTER TABLE "portfolio_performance_records" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "portfolio_performance_records" FORCE ROW LEVEL SECURITY;
ALTER TABLE "portfolio_position_lots" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "portfolio_position_lots" FORCE ROW LEVEL SECURITY;
ALTER TABLE "portfolio_snapshots" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "portfolio_snapshots" FORCE ROW LEVEL SECURITY;
ALTER TABLE "portfolio_statements" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "portfolio_statements" FORCE ROW LEVEL SECURITY;
ALTER TABLE "portfolio_valuations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "portfolio_valuations" FORCE ROW LEVEL SECURITY;
ALTER TABLE "positions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "positions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "privacy_exports" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "privacy_exports" FORCE ROW LEVEL SECURITY;
ALTER TABLE "privacy_requests" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "privacy_requests" FORCE ROW LEVEL SECURITY;
ALTER TABLE "reconciliation_discrepancies" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "reconciliation_discrepancies" FORCE ROW LEVEL SECURITY;
ALTER TABLE "reconciliation_runs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "reconciliation_runs" FORCE ROW LEVEL SECURITY;
ALTER TABLE "refresh_tokens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "refresh_tokens" FORCE ROW LEVEL SECURITY;
ALTER TABLE "refunds" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "refunds" FORCE ROW LEVEL SECURITY;
ALTER TABLE "research_audit_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "research_audit_logs" FORCE ROW LEVEL SECURITY;
ALTER TABLE "research_backtest_runs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "research_backtest_runs" FORCE ROW LEVEL SECURITY;
ALTER TABLE "research_backtest_snapshots" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "research_backtest_snapshots" FORCE ROW LEVEL SECURITY;
ALTER TABLE "research_backtest_trades" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "research_backtest_trades" FORCE ROW LEVEL SECURITY;
ALTER TABLE "research_datasets" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "research_datasets" FORCE ROW LEVEL SECURITY;
ALTER TABLE "research_paper_fills" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "research_paper_fills" FORCE ROW LEVEL SECURITY;
ALTER TABLE "research_paper_orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "research_paper_orders" FORCE ROW LEVEL SECURITY;
ALTER TABLE "research_paper_sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "research_paper_sessions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "research_paper_snapshots" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "research_paper_snapshots" FORCE ROW LEVEL SECURITY;
ALTER TABLE "research_promotion_requests" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "research_promotion_requests" FORCE ROW LEVEL SECURITY;
ALTER TABLE "research_signals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "research_signals" FORCE ROW LEVEL SECURITY;
ALTER TABLE "research_strategy_versions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "research_strategy_versions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "retention_candidates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "retention_candidates" FORCE ROW LEVEL SECURITY;
ALTER TABLE "risk_configuration_versions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "risk_configuration_versions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "risk_configurations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "risk_configurations" FORCE ROW LEVEL SECURITY;
ALTER TABLE "risk_decision_records" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "risk_decision_records" FORCE ROW LEVEL SECURITY;
ALTER TABLE "risk_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "risk_events" FORCE ROW LEVEL SECURITY;
ALTER TABLE "risk_management_snapshots" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "risk_management_snapshots" FORCE ROW LEVEL SECURITY;
ALTER TABLE "risk_protection_actions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "risk_protection_actions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "risk_reconciliation_records" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "risk_reconciliation_records" FORCE ROW LEVEL SECURITY;
ALTER TABLE "risk_score_records" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "risk_score_records" FORCE ROW LEVEL SECURITY;
ALTER TABLE "risk_snapshot_metadata" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "risk_snapshot_metadata" FORCE ROW LEVEL SECURITY;
ALTER TABLE "saas_audit_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "saas_audit_logs" FORCE ROW LEVEL SECURITY;
ALTER TABLE "security_audit_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "security_audit_logs" FORCE ROW LEVEL SECURITY;
ALTER TABLE "security_threat_signals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "security_threat_signals" FORCE ROW LEVEL SECURITY;
ALTER TABLE "sso_assertion_replays" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sso_assertion_replays" FORCE ROW LEVEL SECURITY;
ALTER TABLE "sso_audit_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sso_audit_events" FORCE ROW LEVEL SECURITY;
ALTER TABLE "sso_auth_transactions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sso_auth_transactions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "sso_configurations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sso_configurations" FORCE ROW LEVEL SECURITY;
ALTER TABLE "sso_identities" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sso_identities" FORCE ROW LEVEL SECURITY;
ALTER TABLE "sso_login_attempts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sso_login_attempts" FORCE ROW LEVEL SECURITY;
ALTER TABLE "strategies" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "strategies" FORCE ROW LEVEL SECURITY;
ALTER TABLE "strategy_checkpoints" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "strategy_checkpoints" FORCE ROW LEVEL SECURITY;
ALTER TABLE "strategy_incidents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "strategy_incidents" FORCE ROW LEVEL SECURITY;
ALTER TABLE "strategy_runs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "strategy_runs" FORCE ROW LEVEL SECURITY;
ALTER TABLE "tenant_api_keys" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tenant_api_keys" FORCE ROW LEVEL SECURITY;
ALTER TABLE "tenant_branding" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tenant_branding" FORCE ROW LEVEL SECURITY;
ALTER TABLE "tenant_domains" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tenant_domains" FORCE ROW LEVEL SECURITY;
ALTER TABLE "tenant_feature_flags" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tenant_feature_flags" FORCE ROW LEVEL SECURITY;
ALTER TABLE "tenant_settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tenant_settings" FORCE ROW LEVEL SECURITY;
ALTER TABLE "tenant_subscriptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tenant_subscriptions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "trader_profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "trader_profiles" FORCE ROW LEVEL SECURITY;
ALTER TABLE "trader_strategies" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "trader_strategies" FORCE ROW LEVEL SECURITY;
ALTER TABLE "trading_accounts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "trading_accounts" FORCE ROW LEVEL SECURITY;
ALTER TABLE "trading_sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "trading_sessions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "trading_symbols" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "trading_symbols" FORCE ROW LEVEL SECURITY;
ALTER TABLE "transaction_monitoring_signals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "transaction_monitoring_signals" FORCE ROW LEVEL SECURITY;
ALTER TABLE "usage_alert_configs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "usage_alert_configs" FORCE ROW LEVEL SECURITY;
ALTER TABLE "usage_alert_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "usage_alert_events" FORCE ROW LEVEL SECURITY;
ALTER TABLE "usage_buckets" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "usage_buckets" FORCE ROW LEVEL SECURITY;
ALTER TABLE "usage_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "usage_events" FORCE ROW LEVEL SECURITY;
ALTER TABLE "usage_meters" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "usage_meters" FORCE ROW LEVEL SECURITY;
ALTER TABLE "user_roles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_roles" FORCE ROW LEVEL SECURITY;
ALTER TABLE "user_sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_sessions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "users" FORCE ROW LEVEL SECURITY;
ALTER TABLE "verification_tokens" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "verification_tokens" FORCE ROW LEVEL SECURITY;
ALTER TABLE "webhook_delivery_attempts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "webhook_delivery_attempts" FORCE ROW LEVEL SECURITY;
ALTER TABLE "webhook_subscriptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "webhook_subscriptions" FORCE ROW LEVEL SECURITY;
ALTER TABLE "withdrawal_requests" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "withdrawal_requests" FORCE ROW LEVEL SECURITY;

-- --- post-enable verification (manual, expect each count to match the
-- --- seeded tenant's own rows under that tenant's GUC, and zero without) --
-- BEGIN; SELECT set_config('app.tenant_id', '<tenant-uuid>', true);
--   SELECT count(*) FROM "account_balance_snapshots";
--   SELECT count(*) FROM "account_ownerships";
--   SELECT count(*) FROM "account_relationships";
-- ROLLBACK;
-- Without the GUC, every covered table must read 0 rows as the app role.

-- Excluded (platform-scoped, nullable tenantId) - intentionally untouched:
--   audit_logs (AuditLog)
--   circuit_breaker_records (CircuitBreakerRecord)
--   compliance_policy_records (CompliancePolicyRecord)
--   institutional_risk_policies (InstitutionalRiskPolicy)
--   kill_switches (KillSwitch)
--   legal_holds (LegalHold)
--   mobile_reconciliation_findings (MobileReconciliationFinding)
--   mobile_release_audits (MobileReleaseAudit)
--   operational_actions (OperationalAction)
--   operational_audit_logs (OperationalAuditLog)
--   operational_dependency_checks (OperationalDependencyCheck)
--   operational_incident_events (OperationalIncidentEvent)
--   operational_incidents (OperationalIncident)
--   operational_maintenance_windows (OperationalMaintenanceWindow)
--   operational_readiness_checks (OperationalReadinessCheck)
--   operational_reconciliation_runs (OperationalReconciliationRun)
--   operational_recovery_runs (OperationalRecoveryRun)
--   operational_service_degradations (OperationalServiceDegradation)
--   ops_alerts (OpsAlert)
--   ops_incidents (OpsIncident)
--   partner_attributions (PartnerAttribution)
--   partner_audits (PartnerAudit)
--   partner_commissions (PartnerCommission)
--   partner_tenant_relationships (PartnerTenantRelationship)
--   plans (Plan)
--   roles (Role)
--   security_events (SecurityEvent)
--   security_policies (SecurityPolicy)
--   subscription_plans (SubscriptionPlan)
--   webhook_events (WebhookEvent)
