-- Part 11 (migration: functions + policies (NOT enabling)). Generated by scripts/gen_part11_rls.py - do not hand-edit;
-- rerun the generator. Schema stamp: 20261008130000.
--
-- Row-level security is the layer BELOW the tenant-scoped Prisma factory: the
-- factory cannot forget its WHERE, and even if a path bypassed the factory,
-- the database would still refuse the row. No GUC means no rows:
-- `wlct_current_tenant_id()` returns NULL when `app.tenant_id` is unset, and
-- `tenant_id = NULL` is never true - fail-closed, which is the only
-- acceptable default for a defence layer.

-- The single source of the request's tenant, read from the transaction-local
-- GUC that PrismaService.withTenantRls() sets via set_config(..., true).
-- STABLE so the planner evaluates it once per query, not per row.
CREATE OR REPLACE FUNCTION wlct_current_tenant_id() RETURNS uuid
LANGUAGE sql STABLE
AS $$ SELECT nullif(current_setting('app.tenant_id', true), '')::uuid $$;

-- OutboxEvent
CREATE POLICY tenant_isolation ON "outbox_events"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- Deliberately NOT enabled here. `ALTER TABLE ... ENABLE ROW LEVEL SECURITY`
-- (and FORCE) is the prisma/rls/enable.sql DBA step, run only after the
-- pre-flight checklist there passes - enabling before every write path
-- adopts withTenantRls() turns defence into outage, and that trade is made
-- once, on purpose, by a human with the checklist.
--
-- Excluded by design (nullable tenantId; platform-scoped rows):

--   audit_logs                         (AuditLog)
--   circuit_breaker_records            (CircuitBreakerRecord)
--   compliance_policy_records          (CompliancePolicyRecord)
--   institutional_risk_policies        (InstitutionalRiskPolicy)
--   kill_switches                      (KillSwitch)
--   legal_holds                        (LegalHold)
--   mobile_reconciliation_findings     (MobileReconciliationFinding)
--   mobile_release_audits              (MobileReleaseAudit)
--   operational_actions                (OperationalAction)
--   operational_audit_logs             (OperationalAuditLog)
--   operational_dependency_checks      (OperationalDependencyCheck)
--   operational_incident_events        (OperationalIncidentEvent)
--   operational_incidents              (OperationalIncident)
--   operational_maintenance_windows    (OperationalMaintenanceWindow)
--   operational_readiness_checks       (OperationalReadinessCheck)
--   operational_reconciliation_runs    (OperationalReconciliationRun)
--   operational_recovery_runs          (OperationalRecoveryRun)
--   operational_service_degradations   (OperationalServiceDegradation)
--   ops_alerts                         (OpsAlert)
--   ops_incidents                      (OpsIncident)
--   partner_attributions               (PartnerAttribution)
--   partner_audits                     (PartnerAudit)
--   partner_commissions                (PartnerCommission)
--   partner_tenant_relationships       (PartnerTenantRelationship)
--   plans                              (Plan)
--   roles                              (Role)
--   security_events                    (SecurityEvent)
--   security_policies                  (SecurityPolicy)
--   subscription_plans                 (SubscriptionPlan)
--   webhook_events                     (WebhookEvent)
-- Their tenant-bearing rows remain filtered by the tenant-scoped factory;
-- a strict policy here would hide the NULL-tenant platform rows that are
-- nobody's cross-tenant secret. The exclusion is a decision, listed in
-- rls_coverage.json and pinned by rls-coverage.spec.ts - never an oversight.
