-- Plan catalogue tables (plans, plan_features, plan_limits).
--
-- The billing plans service (apps/api/src/modules/billing/plans/) and its
-- repository were written against a `Plan` model with first-class
-- `PlanFeature` and `PlanLimit` relations; this migration ships the three
-- tables that model describes, in lockstep with
-- apps/api/prisma/schema.prisma, exactly as every prior migration does.
--
-- Shape decisions, each borrowed from a table that already had to make it:
--   - `plans.tenant_id` is NULLABLE: NULL rows are the platform catalogue
--     every tenant sees, the same convention `subscription_plans` uses. This
--     also places the catalogue in the Part 11 RLS "excluded (platform-scoped,
--     nullable tenantId)" set, like `subscription_plans` -- the plans service
--     scopes every query by tenantId in code.
--   - Text ids (`cuid()`): the plan catalogue seeds fixed, human-readable ids
--     ("plan-free", "plan-basic", ...) and a tenant-provided column cannot be
--     a UUID. `plan_features.plan_id` / `plan_limits.plan_id` cascade on
--     delete: features and limits have no meaning without their plan.
--   - `price` is JSON: the service stores the structured price object
--     (amount, currency, interval, trialDays) as one value, matching the
--     repository's single-column read.
--   - `plan_features` and `plan_limits` are unique on (plan_id, key): a plan
--     cannot declare the same feature or limit twice.
--
-- No GRANT/RLS statements here: as with every prior migration, policy
-- creation for tenant-owned tables is generated by the Part 11 machinery into
-- its own artefacts, and this catalogue is intentionally in the excluded set.

-- CreateEnumType
CREATE TYPE "PlanTier" AS ENUM ('free', 'basic', 'standard', 'premium', 'enterprise');

-- CreateEnumType
CREATE TYPE "PlanStatus" AS ENUM ('active', 'inactive', 'deprecated', 'archived');

-- CreateTable
CREATE TABLE "plans" (
    "id" TEXT NOT NULL,
    "tenant_id" TEXT,
    "name" VARCHAR(120) NOT NULL,
    "slug" VARCHAR(64) NOT NULL,
    "description" VARCHAR(500),
    "tier" "PlanTier" NOT NULL DEFAULT 'free',
    "status" "PlanStatus" NOT NULL DEFAULT 'active',
    "price" JSONB NOT NULL,
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "created_by" VARCHAR(64) NOT NULL,
    "updated_by" VARCHAR(64) NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "plans_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "plan_features" (
    "id" TEXT NOT NULL,
    "plan_id" TEXT NOT NULL,
    "key" VARCHAR(64) NOT NULL,
    "name" VARCHAR(120) NOT NULL,
    "description" VARCHAR(500) NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "limit" INTEGER,
    "unit" VARCHAR(32),

    CONSTRAINT "plan_features_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "plan_limits" (
    "id" TEXT NOT NULL,
    "plan_id" TEXT NOT NULL,
    "key" VARCHAR(64) NOT NULL,
    "name" VARCHAR(120) NOT NULL,
    "description" VARCHAR(500) NOT NULL,
    "value" INTEGER NOT NULL,
    "unit" VARCHAR(32) NOT NULL,
    "hard_limit" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "plan_limits_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "plans_tenant_id_slug_key" ON "plans"("tenant_id", "slug");

-- CreateIndex
CREATE INDEX "plans_tenant_id_status_idx" ON "plans"("tenant_id", "status");

-- CreateIndex
CREATE INDEX "plans_tenant_id_tier_idx" ON "plans"("tenant_id", "tier");

-- CreateIndex
CREATE UNIQUE INDEX "plan_features_plan_id_key_key" ON "plan_features"("plan_id", "key");

-- CreateIndex
CREATE INDEX "plan_features_plan_id_idx" ON "plan_features"("plan_id");

-- CreateIndex
CREATE UNIQUE INDEX "plan_limits_plan_id_key_key" ON "plan_limits"("plan_id", "key");

-- CreateIndex
CREATE INDEX "plan_limits_plan_id_idx" ON "plan_limits"("plan_id");

-- AddForeignKey
ALTER TABLE "plan_features" ADD CONSTRAINT "plan_features_plan_id_fkey" FOREIGN KEY ("plan_id") REFERENCES "plans"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "plan_limits" ADD CONSTRAINT "plan_limits_plan_id_fkey" FOREIGN KEY ("plan_id") REFERENCES "plans"("id") ON DELETE CASCADE ON UPDATE CASCADE;
