// # NEW — Generates SDK OpenAPI types and runtime event constants from the committed OpenAPI spec

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const sdkRoot = resolve(scriptDirectory, '..');
const repositoryRoot = resolve(sdkRoot, '../..');
const specPath = resolve(repositoryRoot, 'docs/openapi/openapi.json');
const generatedSchemaPath = resolve(sdkRoot, 'src/generated/schema.d.ts');
const generatedEventTypesPath = resolve(sdkRoot, 'src/generated/event-types.ts');
const checkOnly = process.argv.includes('--check');

function eventTypesFromSpec(document) {
  const eventTypes = document.components?.schemas?.DeveloperWebhookEventEnvelope?.properties?.eventType?.enum;
  if (!Array.isArray(eventTypes) || eventTypes.length === 0 || eventTypes.some((eventType) => typeof eventType !== 'string')) {
    throw new Error('OpenAPI DeveloperWebhookEventEnvelope.eventType.enum is missing or invalid');
  }
  const unique = [...new Set(eventTypes)];
  if (unique.length !== eventTypes.length) throw new Error('OpenAPI webhook event catalog contains duplicates');
  return unique.sort((left, right) => left < right ? -1 : left > right ? 1 : 0);
}

async function expectedFile(path, content) {
  if (checkOnly) {
    let current;
    try {
      current = await readFile(path, 'utf8');
    } catch {
      throw new Error(`${path.slice(sdkRoot.length + 1)} is missing; run npm run generate --workspace @wlct/sdk-typescript`);
    }
    if (current !== content) {
      throw new Error(`${path.slice(sdkRoot.length + 1)} is stale; run npm run generate --workspace @wlct/sdk-typescript`);
    }
    return;
  }
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content, 'utf8');
}

async function main() {
  const document = JSON.parse(await readFile(specPath, 'utf8'));
  const eventTypes = eventTypesFromSpec(document);
  const ast = await openapiTS(document, { alphabetize: true, immutable: true });
  const schemaContent = [
    '/**',
    ' * Generated from docs/openapi/openapi.json by packages/sdk-typescript/scripts/generate.mjs.',
    ' * Do not edit this file directly.',
    ' */',
    astToString(ast).trimEnd(),
    '',
  ].join('\n');
  const eventTypesContent = [
    '/**',
    ' * Generated from docs/openapi/openapi.json by packages/sdk-typescript/scripts/generate.mjs.',
    ' * Do not edit this file directly.',
    ' */',
    'export const DEVELOPER_EVENT_TYPES = [',
    ...eventTypes.map((eventType) => `  ${JSON.stringify(eventType)},`),
    '] as const;',
    '',
    'export type DeveloperEventType = (typeof DEVELOPER_EVENT_TYPES)[number];',
    '',
  ].join('\n');

  await expectedFile(generatedSchemaPath, schemaContent);
  await expectedFile(generatedEventTypesPath, eventTypesContent);
  process.stdout.write(`${checkOnly ? 'Verified' : 'Generated'} TypeScript SDK contracts for ${eventTypes.length} webhook event types.\n`);
}

main().catch((error) => {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
  process.exitCode = 1;
});
