-- Part 11 (migration: functions + policies (NOT enabling)). Generated by scripts/gen_part11_rls.py - do not hand-edit;
-- rerun the generator. Schema stamp: 20260923090000.
--
-- Row-level security is the layer BELOW the tenant-scoped Prisma factory: the
-- factory cannot forget its WHERE, and even if a path bypassed the factory,
-- the database would still refuse the row. No GUC means no rows:
-- `wlct_current_tenant_id()` returns NULL when `app.tenant_id` is unset, and
-- `tenant_id = NULL` is never true - fail-closed, which is the only
-- acceptable default for a defence layer.

-- The single source of the request's tenant, read from the transaction-local
-- GUC that PrismaService.withTenantRls() sets via set_config(..., true).
-- STABLE so the planner evaluates it once per query, not per row.
CREATE OR REPLACE FUNCTION wlct_current_tenant_id() RETURNS uuid
LANGUAGE sql STABLE
AS $$ SELECT nullif(current_setting('app.tenant_id', true), '')::uuid $$;

-- AccountBalanceSnapshot
CREATE POLICY tenant_isolation ON "account_balance_snapshots"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- AccountOwnership
CREATE POLICY tenant_isolation ON "account_ownerships"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- AccountRelationship
CREATE POLICY tenant_isolation ON "account_relationships"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- AccountRestriction
CREATE POLICY tenant_isolation ON "account_restrictions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- BacktestMetric
CREATE POLICY tenant_isolation ON "backtest_metrics"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- BacktestRun
CREATE POLICY tenant_isolation ON "backtest_runs"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- BacktestTrade
CREATE POLICY tenant_isolation ON "backtest_trades"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- BillingCustomer
CREATE POLICY tenant_isolation ON "billing_customers"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- BillingLedgerEntry
CREATE POLICY tenant_isolation ON "billing_ledger_entries"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- BillingNotificationAuditLog
CREATE POLICY tenant_isolation ON "billing_notification_audit_logs"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- BillingNotificationJob
CREATE POLICY tenant_isolation ON "billing_notification_jobs"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- BillingNotificationPreference
CREATE POLICY tenant_isolation ON "billing_notification_preferences"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ClientLifecycleAudit
CREATE POLICY tenant_isolation ON "client_lifecycle_audits"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ClientOnboardingStep
CREATE POLICY tenant_isolation ON "client_onboarding_steps"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ClientOnboarding
CREATE POLICY tenant_isolation ON "client_onboardings"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ClientProfile
CREATE POLICY tenant_isolation ON "client_profiles"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ClientReview
CREATE POLICY tenant_isolation ON "client_reviews"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ComplianceAuditLog
CREATE POLICY tenant_isolation ON "compliance_audit_logs"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ComplianceCase
CREATE POLICY tenant_isolation ON "compliance_cases"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ComplianceEvidence
CREATE POLICY tenant_isolation ON "compliance_evidences"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ComplianceReportCertification
CREATE POLICY tenant_isolation ON "compliance_report_certifications"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ComplianceReportDelivery
CREATE POLICY tenant_isolation ON "compliance_report_deliveries"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ComplianceReportValidation
CREATE POLICY tenant_isolation ON "compliance_report_validations"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ComplianceReport
CREATE POLICY tenant_isolation ON "compliance_reports"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ComplianceReview
CREATE POLICY tenant_isolation ON "compliance_reviews"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ComplianceScreeningRequest
CREATE POLICY tenant_isolation ON "compliance_screening_requests"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ConsentRecord
CREATE POLICY tenant_isolation ON "consent_records"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- CopyExecution
CREATE POLICY tenant_isolation ON "copy_executions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- CopyReconciliationRecord
CREATE POLICY tenant_isolation ON "copy_reconciliation_records"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- CopySubscription
CREATE POLICY tenant_isolation ON "copy_subscriptions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- CopyTradingAuditLog
CREATE POLICY tenant_isolation ON "copy_trading_audit_logs"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- CustodyAudit
CREATE POLICY tenant_isolation ON "custody_audits"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- CustodyDeposit
CREATE POLICY tenant_isolation ON "custody_deposits"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- CustodyInternalTransfer
CREATE POLICY tenant_isolation ON "custody_internal_transfers"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- CustodyReconciliation
CREATE POLICY tenant_isolation ON "custody_reconciliations"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- CustodyReserve
CREATE POLICY tenant_isolation ON "custody_reserves"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- CustodySweep
CREATE POLICY tenant_isolation ON "custody_sweeps"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- CustodyTransactionConfirmation
CREATE POLICY tenant_isolation ON "custody_transaction_confirmations"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- CustodyTransaction
CREATE POLICY tenant_isolation ON "custody_transactions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- CustodyWalletAddress
CREATE POLICY tenant_isolation ON "custody_wallet_addresses"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- CustodyWallet
CREATE POLICY tenant_isolation ON "custody_wallets"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- CustodyWithdrawal
CREATE POLICY tenant_isolation ON "custody_withdrawals"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- DeveloperAccessToken
CREATE POLICY tenant_isolation ON "developer_access_tokens"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- DeveloperApplication
CREATE POLICY tenant_isolation ON "developer_applications"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- DeveloperAudit
CREATE POLICY tenant_isolation ON "developer_audit"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- DeveloperCredential
CREATE POLICY tenant_isolation ON "developer_credentials"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- DeveloperEventSubscription
CREATE POLICY tenant_isolation ON "developer_event_subscriptions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- DeveloperOAuthGrant
CREATE POLICY tenant_isolation ON "developer_oauth_grants"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- DeveloperWebhookDelivery
CREATE POLICY tenant_isolation ON "developer_webhook_deliveries"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- DeveloperWebhookSubscription
CREATE POLICY tenant_isolation ON "developer_webhook_subscriptions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- DeviceTrust
CREATE POLICY tenant_isolation ON "device_trusts"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- DunningCase
CREATE POLICY tenant_isolation ON "dunning_cases"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ExecutionEngineIncident
CREATE POLICY tenant_isolation ON "engine_incidents"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ExecutionOrderEvent
CREATE POLICY tenant_isolation ON "engine_order_events"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ExecutionOrderFill
CREATE POLICY tenant_isolation ON "engine_order_fills"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ExecutionOrder
CREATE POLICY tenant_isolation ON "engine_orders"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ExecutionRetentionRun
CREATE POLICY tenant_isolation ON "engine_retention_runs"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- EnterpriseApiKey
CREATE POLICY tenant_isolation ON "enterprise_api_keys"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- EvidencePackage
CREATE POLICY tenant_isolation ON "evidence_packages"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ExchangeStreamSession
CREATE POLICY tenant_isolation ON "exchange_stream_sessions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ExecutionIncident
CREATE POLICY tenant_isolation ON "execution_incidents"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- FeeAccrual
CREATE POLICY tenant_isolation ON "fee_accruals"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- FeeAuditLog
CREATE POLICY tenant_isolation ON "fee_audit_logs"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- FeeSettlementItem
CREATE POLICY tenant_isolation ON "fee_settlement_items"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- FeeSettlement
CREATE POLICY tenant_isolation ON "fee_settlements"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- FinanceAuditLog
CREATE POLICY tenant_isolation ON "finance_audit_logs"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- FundingApproval
CREATE POLICY tenant_isolation ON "funding_approvals"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- FundingReconciliation
CREATE POLICY tenant_isolation ON "funding_reconciliations"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- FundingRequest
CREATE POLICY tenant_isolation ON "funding_requests"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- GovernanceAction
CREATE POLICY tenant_isolation ON "governance_actions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- GovernanceAudit
CREATE POLICY tenant_isolation ON "governance_audits"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- GovernanceDataClassification
CREATE POLICY tenant_isolation ON "governance_data_classifications"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- GovernanceDataInventory
CREATE POLICY tenant_isolation ON "governance_data_inventory"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- GovernanceReconciliation
CREATE POLICY tenant_isolation ON "governance_reconciliations"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- InstitutionalAccount
CREATE POLICY tenant_isolation ON "institutional_accounts"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- Invoice
CREATE POLICY tenant_isolation ON "invoices"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- KycProfile
CREATE POLICY tenant_isolation ON "kyc_profiles"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- LoginAttempt
CREATE POLICY tenant_isolation ON "login_attempts"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- MobileApplication
CREATE POLICY tenant_isolation ON "mobile_applications"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- MobileArtifact
CREATE POLICY tenant_isolation ON "mobile_artifacts"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- MobileBuild
CREATE POLICY tenant_isolation ON "mobile_builds"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- MobileCrashEvent
CREATE POLICY tenant_isolation ON "mobile_crash_events"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- MobileReleaseApproval
CREATE POLICY tenant_isolation ON "mobile_release_approvals"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- MobileReleaseRollout
CREATE POLICY tenant_isolation ON "mobile_release_rollouts"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- MobileRelease
CREATE POLICY tenant_isolation ON "mobile_releases"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- MobileSecurityScan
CREATE POLICY tenant_isolation ON "mobile_security_scans"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- MobileStoreSubmission
CREATE POLICY tenant_isolation ON "mobile_store_submissions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- Notification
CREATE POLICY tenant_isolation ON "notifications"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- OmsAllocation
CREATE POLICY tenant_isolation ON "oms_allocations"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- OmsAudit
CREATE POLICY tenant_isolation ON "oms_audits"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- OmsExecutionAck
CREATE POLICY tenant_isolation ON "oms_execution_acks"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- OmsExecutionLatency
CREATE POLICY tenant_isolation ON "oms_execution_latency"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- OmsExecutionQuality
CREATE POLICY tenant_isolation ON "oms_execution_quality"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- OmsFill
CREATE POLICY tenant_isolation ON "oms_fills"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- OmsOperational
CREATE POLICY tenant_isolation ON "oms_operational"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- OmsOrderIntent
CREATE POLICY tenant_isolation ON "oms_order_intents"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- OmsPostTrade
CREATE POLICY tenant_isolation ON "oms_post_trades"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- OmsReconciliation
CREATE POLICY tenant_isolation ON "oms_reconciliations"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- OmsRejection
CREATE POLICY tenant_isolation ON "oms_rejections"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- OmsTrade
CREATE POLICY tenant_isolation ON "oms_trades"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- OmsVenueScore
CREATE POLICY tenant_isolation ON "oms_venue_scores"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- Order
CREATE POLICY tenant_isolation ON "orders"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- OverageRecord
CREATE POLICY tenant_isolation ON "overage_records"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- PaperPortfolioSnapshot
CREATE POLICY tenant_isolation ON "paper_portfolio_snapshots"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- PaperTradingSession
CREATE POLICY tenant_isolation ON "paper_trading_sessions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- Payment
CREATE POLICY tenant_isolation ON "payments"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- Payout
CREATE POLICY tenant_isolation ON "payouts"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- PortfolioAccountingAdjustment
CREATE POLICY tenant_isolation ON "portfolio_accounting_adjustments"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- PortfolioAccountingClose
CREATE POLICY tenant_isolation ON "portfolio_accounting_closes"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- PortfolioAccountingEvent
CREATE POLICY tenant_isolation ON "portfolio_accounting_events"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- PortfolioAccountingPeriod
CREATE POLICY tenant_isolation ON "portfolio_accounting_periods"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- PortfolioAccountingProfile
CREATE POLICY tenant_isolation ON "portfolio_accounting_profiles"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- PortfolioAccountingReconciliation
CREATE POLICY tenant_isolation ON "portfolio_accounting_reconciliations"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- PortfolioAttributionRecord
CREATE POLICY tenant_isolation ON "portfolio_attribution_records"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- PortfolioCashLedgerEntry
CREATE POLICY tenant_isolation ON "portfolio_cash_ledger_entries"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- PortfolioPerformanceRecord
CREATE POLICY tenant_isolation ON "portfolio_performance_records"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- PortfolioPositionLot
CREATE POLICY tenant_isolation ON "portfolio_position_lots"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- PortfolioSnapshot
CREATE POLICY tenant_isolation ON "portfolio_snapshots"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- PortfolioStatement
CREATE POLICY tenant_isolation ON "portfolio_statements"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- PortfolioValuation
CREATE POLICY tenant_isolation ON "portfolio_valuations"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- Position
CREATE POLICY tenant_isolation ON "positions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- PrivacyExport
CREATE POLICY tenant_isolation ON "privacy_exports"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- PrivacyRequest
CREATE POLICY tenant_isolation ON "privacy_requests"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ReconciliationDiscrepancy
CREATE POLICY tenant_isolation ON "reconciliation_discrepancies"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ReconciliationRun
CREATE POLICY tenant_isolation ON "reconciliation_runs"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- RefreshToken
CREATE POLICY tenant_isolation ON "refresh_tokens"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- Refund
CREATE POLICY tenant_isolation ON "refunds"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ResearchAuditLog
CREATE POLICY tenant_isolation ON "research_audit_logs"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ResearchBacktestRun
CREATE POLICY tenant_isolation ON "research_backtest_runs"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ResearchBacktestSnapshot
CREATE POLICY tenant_isolation ON "research_backtest_snapshots"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ResearchBacktestTrade
CREATE POLICY tenant_isolation ON "research_backtest_trades"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ResearchDataset
CREATE POLICY tenant_isolation ON "research_datasets"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ResearchPaperFill
CREATE POLICY tenant_isolation ON "research_paper_fills"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ResearchPaperOrder
CREATE POLICY tenant_isolation ON "research_paper_orders"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ResearchPaperSession
CREATE POLICY tenant_isolation ON "research_paper_sessions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ResearchPaperSnapshot
CREATE POLICY tenant_isolation ON "research_paper_snapshots"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ResearchPromotionRequest
CREATE POLICY tenant_isolation ON "research_promotion_requests"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ResearchSignal
CREATE POLICY tenant_isolation ON "research_signals"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- ResearchStrategyVersion
CREATE POLICY tenant_isolation ON "research_strategy_versions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- RetentionCandidate
CREATE POLICY tenant_isolation ON "retention_candidates"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- RiskConfigurationVersion
CREATE POLICY tenant_isolation ON "risk_configuration_versions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- RiskConfiguration
CREATE POLICY tenant_isolation ON "risk_configurations"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- RiskDecisionRecord
CREATE POLICY tenant_isolation ON "risk_decision_records"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- RiskEvent
CREATE POLICY tenant_isolation ON "risk_events"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- RiskManagementSnapshot
CREATE POLICY tenant_isolation ON "risk_management_snapshots"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- RiskProtectionTrip
CREATE POLICY tenant_isolation ON "risk_protection_actions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- RiskReconciliationRecord
CREATE POLICY tenant_isolation ON "risk_reconciliation_records"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- RiskScoreRecord
CREATE POLICY tenant_isolation ON "risk_score_records"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- RiskSnapshotMetadata
CREATE POLICY tenant_isolation ON "risk_snapshot_metadata"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- SaasAuditLog
CREATE POLICY tenant_isolation ON "saas_audit_logs"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- SecurityAuditLog
CREATE POLICY tenant_isolation ON "security_audit_logs"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- SecurityThreatSignal
CREATE POLICY tenant_isolation ON "security_threat_signals"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- SsoAssertionReplay
CREATE POLICY tenant_isolation ON "sso_assertion_replays"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- SsoAuditEvent
CREATE POLICY tenant_isolation ON "sso_audit_events"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- SsoAuthTransaction
CREATE POLICY tenant_isolation ON "sso_auth_transactions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- SsoConfiguration
CREATE POLICY tenant_isolation ON "sso_configurations"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- SsoIdentity
CREATE POLICY tenant_isolation ON "sso_identities"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- SsoLoginAttempt
CREATE POLICY tenant_isolation ON "sso_login_attempts"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- Strategy
CREATE POLICY tenant_isolation ON "strategies"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- StrategyCheckpoint
CREATE POLICY tenant_isolation ON "strategy_checkpoints"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- StrategyIncident
CREATE POLICY tenant_isolation ON "strategy_incidents"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- StrategyRun
CREATE POLICY tenant_isolation ON "strategy_runs"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- TenantApiKey
CREATE POLICY tenant_isolation ON "tenant_api_keys"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- TenantBranding
CREATE POLICY tenant_isolation ON "tenant_branding"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- TenantDomain
CREATE POLICY tenant_isolation ON "tenant_domains"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- TenantFeatureFlag
CREATE POLICY tenant_isolation ON "tenant_feature_flags"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- TenantSetting
CREATE POLICY tenant_isolation ON "tenant_settings"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- TenantSubscription
CREATE POLICY tenant_isolation ON "tenant_subscriptions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- TraderProfile
CREATE POLICY tenant_isolation ON "trader_profiles"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- TraderStrategy
CREATE POLICY tenant_isolation ON "trader_strategies"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- TradingAccount
CREATE POLICY tenant_isolation ON "trading_accounts"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- TradingSession
CREATE POLICY tenant_isolation ON "trading_sessions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- TradingSymbol
CREATE POLICY tenant_isolation ON "trading_symbols"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- TransactionMonitoringSignal
CREATE POLICY tenant_isolation ON "transaction_monitoring_signals"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- UsageAlertConfig
CREATE POLICY tenant_isolation ON "usage_alert_configs"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- UsageAlertEvent
CREATE POLICY tenant_isolation ON "usage_alert_events"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- UsageBucket
CREATE POLICY tenant_isolation ON "usage_buckets"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- UsageEvent
CREATE POLICY tenant_isolation ON "usage_events"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- UsageMeter
CREATE POLICY tenant_isolation ON "usage_meters"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- UserRole
CREATE POLICY tenant_isolation ON "user_roles"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- UserSession
CREATE POLICY tenant_isolation ON "user_sessions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- User
CREATE POLICY tenant_isolation ON "users"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- VerificationToken
CREATE POLICY tenant_isolation ON "verification_tokens"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- WebhookDeliveryAttempt
CREATE POLICY tenant_isolation ON "webhook_delivery_attempts"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- WebhookSubscription
CREATE POLICY tenant_isolation ON "webhook_subscriptions"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- WithdrawalRequest
CREATE POLICY tenant_isolation ON "withdrawal_requests"
    AS PERMISSIVE
    FOR ALL
    TO PUBLIC
    USING (tenant_id = wlct_current_tenant_id())
    WITH CHECK (tenant_id = wlct_current_tenant_id());

-- Deliberately NOT enabled here. `ALTER TABLE ... ENABLE ROW LEVEL SECURITY`
-- (and FORCE) is the prisma/rls/enable.sql DBA step, run only after the
-- pre-flight checklist there passes - enabling before every write path
-- adopts withTenantRls() turns defence into outage, and that trade is made
-- once, on purpose, by a human with the checklist.
--
-- Excluded by design (nullable tenantId; platform-scoped rows):

--   audit_logs                         (AuditLog)
--   circuit_breaker_records            (CircuitBreakerRecord)
--   compliance_policy_records          (CompliancePolicyRecord)
--   institutional_risk_policies        (InstitutionalRiskPolicy)
--   kill_switches                      (KillSwitch)
--   legal_holds                        (LegalHold)
--   mobile_reconciliation_findings     (MobileReconciliationFinding)
--   mobile_release_audits              (MobileReleaseAudit)
--   operational_actions                (OperationalAction)
--   operational_audit_logs             (OperationalAuditLog)
--   operational_dependency_checks      (OperationalDependencyCheck)
--   operational_incident_events        (OperationalIncidentEvent)
--   operational_incidents              (OperationalIncident)
--   operational_maintenance_windows    (OperationalMaintenanceWindow)
--   operational_readiness_checks       (OperationalReadinessCheck)
--   operational_reconciliation_runs    (OperationalReconciliationRun)
--   operational_recovery_runs          (OperationalRecoveryRun)
--   operational_service_degradations   (OperationalServiceDegradation)
--   ops_alerts                         (OpsAlert)
--   ops_incidents                      (OpsIncident)
--   partner_attributions               (PartnerAttribution)
--   partner_audits                     (PartnerAudit)
--   partner_commissions                (PartnerCommission)
--   partner_tenant_relationships       (PartnerTenantRelationship)
--   plans                              (Plan)
--   roles                              (Role)
--   security_events                    (SecurityEvent)
--   security_policies                  (SecurityPolicy)
--   subscription_plans                 (SubscriptionPlan)
--   webhook_events                     (WebhookEvent)
-- Their tenant-bearing rows remain filtered by the tenant-scoped factory;
-- a strict policy here would hide the NULL-tenant platform rows that are
-- nobody's cross-tenant secret. The exclusion is a decision, listed in
-- rls_coverage.json and pinned by rls-coverage.spec.ts - never an oversight.
