"use client";
import { useState } from "react";
import { reportingApi, type StatementExportFormat } from "@/api/reporting-api";
import { ApiError } from "@/api/api-errors";
import { InlineError } from "@/components/error-state";
import { saveBlob } from "@/lib/save-blob";

/**
 * Exports a persisted statement. The backend returns the file content inline
 * (CSV or JSON) after checking the caller may see the statement's profile; the
 * browser saves it locally. Nothing is computed client-side.
 */
export function ReportDownload({
  statementId,
}: {
  statementId: string;
}): JSX.Element {
  const [pending, setPending] = useState<StatementExportFormat | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleDownload = async (
    format: StatementExportFormat,
  ): Promise<void> => {
    setPending(format);
    setError(null);
    try {
      const { blob, filename } = await reportingApi.exportStatement(
        statementId,
        format,
      );
      saveBlob(blob, filename);
    } catch (err) {
      setError(
        err instanceof ApiError
          ? err.getUserMessage()
          : "The statement could not be exported. Please try again.",
      );
    } finally {
      setPending(null);
    }
  };

  return (
    <div className="rounded border bg-card p-4">
      <h4 className="font-medium">Export</h4>
      <p className="text-xs text-muted">
        Download this statement as generated by the backend.
      </p>
      <div className="mt-2 flex gap-2">
        {(["CSV", "JSON"] as const).map((format) => (
          <button
            key={format}
            type="button"
            onClick={() => void handleDownload(format)}
            disabled={pending !== null}
            className="rounded bg-primary px-4 py-2 text-sm text-white disabled:opacity-50"
          >
            {pending === format ? "Preparing..." : `Download ${format}`}
          </button>
        ))}
      </div>
      {error && (
        <div className="mt-2">
          <InlineError message={error} />
        </div>
      )}
    </div>
  );
}
